FROM nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04

RUN apt update
RUN apt install -y git
RUN apt install -y vim
RUN apt install -y wget
RUN apt install -y python3-dev
RUN apt install -y python3-setuptools
RUN apt install -y python3-pip
RUN pip install torch torchvision torchaudio

CMD ["sleep", "infinity"]
